services:
  - type: web
    name: dashboard-asia-central
    env: python
    rootDir: trabajo_final
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    plan: free
